#!/usr/bin/env python3
import json
import os
import re

# Output directories
APP_WORDS_DIR = os.path.join(os.path.dirname(__file__), "../app/words")
SCRIPTS_GEN_DIR = os.path.join(os.path.dirname(__file__), "generated")
os.makedirs(APP_WORDS_DIR, exist_ok=True)
os.makedirs(SCRIPTS_GEN_DIR, exist_ok=True)

# 1. English Word List (300+ common, clean English nouns)
ENGLISH_WORDS = [
    "air", "alarm", "anchor", "angle", "animal", "answer", "ant", "apple", "apron", "arch",
    "arm", "army", "arrow", "art", "artist", "ash", "asset", "atlas", "attic", "author",
    "avenue", "avocado", "baby", "badge", "bag", "baker", "ball", "balloon", "bamboo", "banana",
    "band", "bank", "bar", "bark", "barn", "barrel", "basket", "bat", "bath", "beach",
    "bead", "beak", "beam", "bean", "bear", "beard", "bed", "bee", "beef", "beetle",
    "bell", "belt", "bench", "berry", "bicycle", "bike", "bird", "biscuit", "blade", "blanket",
    "block", "blood", "blouse", "boat", "bolt", "bone", "book", "boot", "border", "bottle",
    "bowl", "box", "boy", "branch", "bread", "brick", "bridge", "broom", "brother", "brush",
    "bucket", "buckle", "bug", "building", "bulb", "bull", "bus", "bush", "butter", "button",
    "cabin", "cable", "cactus", "cage", "cake", "calendar", "camel", "camera", "camp", "candle",
    "candy", "cannon", "canoe", "cap", "cape", "car", "card", "carpet", "carrot", "castle",
    "cat", "cave", "ceiling", "cell", "cellar", "chain", "chair", "chalk", "cheese", "cherry",
    "chest", "chick", "chicken", "chief", "child", "chimney", "circle", "city", "clam", "cliff",
    "clock", "cloth", "cloud", "clover", "clown", "club", "coach", "coal", "coast", "coat",
    "coconut", "coffee", "coin", "collar", "comb", "comet", "compass", "computer", "cone", "cookie",
    "copper", "cord", "cork", "corn", "corner", "cotton", "couch", "count", "country", "cousin",
    "cow", "crab", "cradle", "crane", "crate", "crayon", "cream", "creek", "cricket", "crown",
    "cube", "cucumber", "cup", "curtain", "cushion", "cyclist", "daisy", "dancer", "deer", "desk",
    "desert", "diamond", "dictionary", "diner", "dinner", "doctor", "dog", "doll", "dolphin", "donkey",
    "door", "dragon", "drawer", "dress", "drum", "duck", "dune", "eagle", "ear", "earth",
    "eel", "egg", "eggplant", "elbow", "elephant", "engine", "envelope", "eye", "face", "factory",
    "fairy", "falcon", "fan", "farm", "farmer", "feather", "fence", "fern", "field", "fig",
    "finger", "fir", "fire", "fish", "flag", "flame", "flamingo", "flash", "flask", "flea",
    "flock", "flood", "floor", "flower", "flute", "fly", "foam", "fog", "foot", "forest",
    "fork", "fossil", "fountain", "fox", "frame", "frog", "fruit", "furnace", "galaxy", "garage",
    "garden", "garlic", "gate", "gazelle", "gem", "ghost", "giant", "gift", "giraffe", "girl",
    "glacier", "glass", "glasses", "glove", "goat", "gold", "goose", "gorilla", "grain", "grape",
    "grass", "greenhouse", "guitar", "gull", "gym", "hair", "hammer", "hamster", "hand", "harbor",
    "harp", "hat", "hawk", "head", "heart", "hedge", "hedgehog", "helmet", "hen", "hero",
    "hill", "hippo", "hive", "hockey", "hoe", "hole", "holly", "honey", "hood", "hook",
    "horn", "horse", "hospital", "hotel", "house", "hunter", "hut", "hyena", "ice", "icicle",
    "igloo", "island", "jacket", "jar", "jasmine", "jay", "jeans", "jelly", "jellyfish", "jewel",
    "journal", "judge", "jug", "juice", "jungle", "kangaroo", "kettle", "key", "kidney", "king",
    "kite", "kitten", "kiwi", "knee", "knife", "knight", "knot", "koala", "label", "lace",
    "ladder", "ladybug", "lake", "lamb", "lamp", "lantern", "laptop", "lark", "lawn", "leaf",
    "lemon", "leopard", "letter", "lettuce", "library", "life", "light", "lighthouse", "lily", "lime",
    "lion", "lizard", "lobster", "lock", "locomotive", "log", "loop", "lotus", "luggage", "lumber",
    "lunch", "magnet", "man", "mango", "map", "maple", "marble", "market", "mask", "match",
    "mat", "meadow", "meat", "melon", "metal", "meteor", "microscope", "milk", "mill", "mind",
    "mirror", "missile", "mole", "monkey", "moon", "moose", "moss", "moth", "mother", "motor",
    "mountain", "mouse", "mouth", "mud", "muffin", "mug", "mule", "muscle", "museum", "mushroom",
    "music", "mustard", "nail", "napkin", "neck", "necklace", "needle", "nest", "net", "newspaper",
    "night", "note", "notebook", "nurse", "nut", "oak", "oar", "oasis", "ocean", "octopus",
    "office", "oil", "olive", "onion", "opal", "orange", "orchid", "organ", "ostrich", "otter",
    "oven", "owl", "ox", "oyster", "pad", "palace", "palm", "pancake", "panda", "panther",
    "paper", "parrot", "parsley", "party", "path", "peach", "peacock", "peanut", "pear", "pearl",
    "pebble", "pen", "pencil", "penguin", "pepper", "person", "piano", "pickle", "picture", "pie",
    "pigeon", "pig", "pillow", "pilot", "pin", "pine", "pineapple", "pipe", "pirate", "pitcher",
    "pizza", "planet", "plank", "plant", "plate", "plum", "pocket", "poem", "poet", "point",
    "pole", "police", "pond", "pony", "pool", "poppy", "porch", "port", "poster", "potato",
    "potter", "powder", "prairie", "priest", "prince", "princess", "printer", "prism", "puddle", "pulse",
    "pump", "pumpkin", "puppy", "pyramid", "queen", "quill", "quilt", "rabbit", "racoon", "radar",
    "radish", "raft", "rail", "rain", "rainbow", "rake", "rat", "raven", "rayon", "ribbon",
    "rice", "ring", "river", "road", "robot", "rock", "rocket", "rod", "roof", "room",
    "rooster", "root", "rope", "rose", "ruby", "rug", "ruler", "sailor", "salad", "salmon",
    "salt", "sand", "sandwich", "sapphire", "sauce", "sausage", "scarf", "school", "scissors", "scooter",
    "scorpion", "screen", "screw", "sculpture", "sea", "seagull", "seal", "seed", "shark", "shed",
    "sheep", "sheet", "shelf", "shell", "shield", "ship", "shirt", "shoe", "shore", "shovel",
    "shower", "shrimp", "shrub", "silk", "silo", "silver", "sink", "sister", "skate", "skeleton",
    "ski", "skin", "skirt", "skull", "skunk", "sky", "slate", "sledge", "sleeve", "slipper",
    "slope", "sloth", "snail", "snake", "snow", "soap", "sock", "sofa", "soil", "soldier",
    "song", "soup", "sparrow", "spear", "spider", "spinach", "sponge", "spoon", "spring", "spruce",
    "squid", "squirrel", "stage", "stamp", "star", "station", "statue", "steak", "steam", "steel",
    "stem", "step", "stick", "stone", "stool", "stork", "storm", "stove", "straw", "strawberry",
    "stream", "street", "string", "student", "submarine", "sugar", "suit", "suitcase", "sun", "sunflower",
    "swan", "sweater", "syrup", "table", "tail", "talent", "tank", "tapestry", "tea", "teacher",
    "teeth", "telescope", "tent", "theater", "thief", "thimble", "thorn", "thread", "tiger", "tile",
    "timber", "tin", "toad", "toast", "toe", "tomato", "tongue", "tool", "tooth", "torch",
    "tornado", "tortoise", "tower", "town", "toy", "track", "tractor", "train", "tray", "tree",
    "triangle", "trolley", "trophy", "trout", "truck", "trumpet", "trunk", "tube", "tulip", "tuna",
    "tunnel", "turkey", "turnip", "turtle", "umbrella", "uncle", "unicorn", "valley", "vase", "vegetable",
    "vehicle", "vest", "village", "vine", "violin", "volcano", "vulture", "wagon", "wall", "walnut",
    "walrus", "wasp", "watch", "water", "waterfall", "wave", "wax", "web", "well", "whale",
    "wheat", "wheel", "whip", "whistle", "window", "wind", "wine", "wing", "wire", "wolf",
    "wood", "wool", "word", "world", "worm", "wreath", "wrist", "yacht", "yam", "yarn",
    "zebra", "zinc", "zipper", "zoo"
]

# 2. German Noun Pool (with accurate grammatical articles: der, die, das)
# Ensures core English equivalents are represented with exact German articles.
GERMAN_WORDS = [
    {"word": "Apfel", "article": "der"},
    {"word": "Haus", "article": "das"},
    {"word": "Wasser", "article": "das"},
    {"word": "Auto", "article": "das"},
    {"word": "Baum", "article": "der"},
    {"word": "Sonne", "article": "die"},
    {"word": "Mond", "article": "der"},
    {"word": "Stern", "article": "der"},
    {"word": "Katze", "article": "die"},
    {"word": "Hund", "article": "der"},
    {"word": "Vogel", "article": "der"},
    {"word": "Fisch", "article": "der"},
    {"word": "Stadt", "article": "die"},
    {"word": "Land", "article": "das"},
    {"word": "Tisch", "article": "der"},
    {"word": "Stuhl", "article": "der"},
    {"word": "Bett", "article": "das"},
    {"word": "Tür", "article": "die"},
    {"word": "Fenster", "article": "das"},
    {"word": "Schlüssel", "article": "der"},
    {"word": "Schuh", "article": "der"},
    {"word": "Hose", "article": "die"},
    {"word": "Hemd", "article": "das"},
    {"word": "Brot", "article": "das"},
    {"word": "Käse", "article": "der"},
    {"word": "Milch", "article": "die"},
    {"word": "Kaffee", "article": "der"},
    {"word": "Tee", "article": "der"},
    {"word": "Uhr", "article": "die"},
    {"word": "Buch", "article": "das"},
    {"word": "Stift", "article": "der"},
    {"word": "Papier", "article": "das"},
    {"word": "Computer", "article": "der"},
    {"word": "Telefon", "article": "das"},
    {"word": "Schule", "article": "die"},
    {"word": "Kind", "article": "das"},
    {"word": "Mann", "article": "der"},
    {"word": "Frau", "article": "die"},
    {"word": "Vater", "article": "der"},
    {"word": "Mutter", "article": "die"},
    {"word": "Bruder", "article": "der"},
    {"word": "Schwester", "article": "die"},
    {"word": "Freund", "article": "der"},
    {"word": "Freundin", "article": "die"},
    {"word": "Arzt", "article": "der"},
    {"word": "Lehrer", "article": "der"},
    {"word": "Schüler", "article": "der"},
    {"word": "Kopf", "article": "der"},
    {"word": "Hand", "article": "die"},
    {"word": "Fuß", "article": "der"},
    {"word": "Auge", "article": "das"},
    {"word": "Ohr", "article": "das"},
    {"word": "Nase", "article": "die"},
    {"word": "Mund", "article": "der"},
    {"word": "Herz", "article": "das"},
    {"word": "Arm", "article": "der"},
    {"word": "Bein", "article": "das"},
    {"word": "Finger", "article": "der"},
    {"word": "Rücken", "article": "der"},
    {"word": "Bauch", "article": "der"},
    {"word": "Nacht", "article": "die"},
    {"word": "Tag", "article": "der"},
    {"word": "Morgen", "article": "der"},
    {"word": "Abend", "article": "der"},
    {"word": "Woche", "article": "die"},
    {"word": "Monat", "article": "der"},
    {"word": "Jahr", "article": "das"},
    {"word": "Sommer", "article": "der"},
    {"word": "Winter", "article": "der"},
    {"word": "Frühling", "article": "der"},
    {"word": "Herbst", "article": "der"},
    {"word": "Regen", "article": "der"},
    {"word": "Schnee", "article": "der"},
    {"word": "Wind", "article": "der"},
    {"word": "Feuer", "article": "das"},
    {"word": "Eis", "article": "das"},
    {"word": "Strand", "article": "der"},
    {"word": "Meer", "article": "das"},
    {"word": "See", "article": "der"},
    {"word": "Fluss", "article": "der"},
    {"word": "Berg", "article": "der"},
    {"word": "Wald", "article": "der"},
    {"word": "Park", "article": "der"},
    {"word": "Blume", "article": "die"},
    {"word": "Gras", "article": "das"},
    {"word": "Blatt", "article": "das"},
    {"word": "Pflanze", "article": "die"},
    {"word": "Garten", "article": "der"},
    {"word": "Spielzeug", "article": "das"},
    {"word": "Fahrrad", "article": "das"},
    {"word": "Zug", "article": "der"},
    {"word": "Bus", "article": "der"},
    {"word": "Flugzeug", "article": "das"},
    {"word": "Schiff", "article": "das"},
    {"word": "Brücke", "article": "die"},
    {"word": "Straße", "article": "die"},
    {"word": "Bild", "article": "das"},
    {"word": "Spiegel", "article": "der"},
    {"word": "Lampe", "article": "die"},
    {"word": "Tasche", "article": "die"},
    {"word": "Koffer", "article": "der"},
    {"word": "Brille", "article": "die"},
    {"word": "Flasche", "article": "die"},
    {"word": "Glas", "article": "das"},
    {"word": "Teller", "article": "der"},
    {"word": "Tasse", "article": "die"},
    {"word": "Messer", "article": "das"},
    {"word": "Gabel", "article": "die"},
    {"word": "Löffel", "article": "der"},
    {"word": "Topf", "article": "der"},
    {"word": "Pfanne", "article": "die"},
    {"word": "Kissen", "article": "das"},
    {"word": "Decke", "article": "die"},
    {"word": "Handtuch", "article": "das"},
    {"word": "Seife", "article": "die"},
    {"word": "Bürste", "article": "die"},
    {"word": "Schrank", "article": "der"},
    {"word": "Raum", "article": "der"},
    {"word": "Zimmer", "article": "das"},
    {"word": "Küche", "article": "die"},
    {"word": "Bad", "article": "das"},
    {"word": "Dorf", "article": "das"},
    {"word": "Geld", "article": "das"},
    {"word": "Karte", "article": "die"},
    {"word": "Ticket", "article": "das"},
    {"word": "Zeitung", "article": "die"},
    {"word": "Zeitschrift", "article": "die"},
    {"word": "Regenschirm", "article": "der"},
    {"word": "Rucksack", "article": "der"},
    {"word": "Kleidung", "article": "die"},
    {"word": "Kleid", "article": "das"},
    {"word": "Jacke", "article": "die"},
    {"word": "Mantel", "article": "der"},
    {"word": "Socke", "article": "die"},
    {"word": "Hut", "article": "der"},
    {"word": "Pullover", "article": "der"},
    {"word": "T-Shirt", "article": "das"},
    {"word": "Junge", "article": "der"},
    {"word": "Mädchen", "article": "das"},
    {"word": "Sohn", "article": "der"},
    {"word": "Tochter", "article": "die"},
    {"word": "Onkel", "article": "der"},
    {"word": "Tante", "article": "die"},
    {"word": "Opa", "article": "der"},
    {"word": "Oma", "article": "die"},
    {"word": "Gast", "article": "der"},
    {"word": "Spieler", "article": "der"},
    {"word": "König", "article": "der"},
    {"word": "Königin", "article": "die"},
    {"word": "Kunde", "article": "der"},
    {"word": "Nachbar", "article": "der"},
    {"word": "Mensch", "article": "der"},
    {"word": "Familie", "article": "die"},
    {"word": "Chef", "article": "der"},
    {"word": "Universität", "article": "die"},
    {"word": "Büro", "article": "das"},
    {"word": "Firma", "article": "die"},
    {"word": "Geschäft", "article": "das"},
    {"word": "Laden", "article": "der"},
    {"word": "Supermarkt", "article": "der"},
    {"word": "Restaurant", "article": "das"},
    {"word": "Hotel", "article": "das"},
    {"word": "Krankenhaus", "article": "das"},
    {"word": "Apotheke", "article": "die"},
    {"word": "Bank", "article": "die"},
    {"word": "Bahnhof", "article": "der"},
    {"word": "Flughafen", "article": "der"},
    {"word": "Platz", "article": "der"},
    {"word": "Insel", "article": "die"},
    {"word": "Kirche", "article": "die"},
    {"word": "Museum", "article": "das"},
    {"word": "Theater", "article": "das"},
    {"word": "Kino", "article": "das"},
    {"word": "Bibliothek", "article": "die"},
    {"word": "Hauptstadt", "article": "die"},
    {"word": "Post", "article": "die"},
    {"word": "Bäckerei", "article": "die"},
    {"word": "Café", "article": "das"},
    {"word": "Markt", "article": "der"},
    {"word": "Wolke", "article": "die"},
    {"word": "Licht", "article": "das"},
    {"word": "Schatten", "article": "der"},
    {"word": "Maus", "article": "die"},
    {"word": "Elefant", "article": "der"},
    {"word": "Löwe", "article": "der"},
    {"word": "Bär", "article": "der"},
    {"word": "Affe", "article": "der"},
    {"word": "Fuchs", "article": "der"},
    {"word": "Wolf", "article": "der"},
    {"word": "Schaf", "article": "das"},
    {"word": "Kuh", "article": "die"},
    {"word": "Schwein", "article": "das"},
    {"word": "Huhn", "article": "das"},
    {"word": "Ente", "article": "die"},
    {"word": "Biene", "article": "die"},
    {"word": "Spinne", "article": "die"},
    {"word": "Mücke", "article": "die"},
    {"word": "Schmetterling", "article": "der"},
    {"word": "Schlange", "article": "die"},
    {"word": "Frosch", "article": "der"},
    {"word": "Kaninchen", "article": "das"},
    {"word": "Pferd", "article": "das"},
    {"word": "Dolphin", "article": "der"},
    {"word": "Hähnchen", "article": "das"},
    {"word": "Wurst", "article": "die"},
    {"word": "Gemüse", "article": "das"},
    {"word": "Obst", "article": "das"},
    {"word": "Banane", "article": "die"},
    {"word": "Orange", "article": "die"},
    {"word": "Kartoffel", "article": "die"},
    {"word": "Tomate", "article": "die"},
    {"word": "Salat", "article": "der"},
    {"word": "Suppe", "article": "die"},
    {"word": "Soße", "article": "die"},
    {"word": "Reis", "article": "der"},
    {"word": "Nudel", "article": "die"},
    {"word": "Zucker", "article": "der"},
    {"word": "Salz", "article": "das"},
    {"word": "Pfeffer", "article": "der"},
    {"word": "Öl", "article": "das"},
    {"word": "Essig", "article": "der"},
    {"word": "Kuchen", "article": "der"},
    {"word": "Schokolade", "article": "die"},
    {"word": "Nuss", "article": "die"},
    {"word": "Honig", "article": "der"},
    {"word": "Marmelade", "article": "die"},
    {"word": "Leben", "article": "das"},
    {"word": "Liebe", "article": "die"},
    {"word": "Glück", "article": "das"},
    {"word": "Freude", "article": "die"},
    {"word": "Angst", "article": "die"},
    {"word": "Traum", "article": "der"},
    {"word": "Gedanke", "article": "der"},
    {"word": "Idee", "article": "die"},
    {"word": "Problem", "article": "das"},
    {"word": "Lösung", "article": "die"},
    {"word": "Frage", "article": "die"},
    {"word": "Antwort", "article": "die"},
    {"word": "Wort", "article": "das"},
    {"word": "Sprache", "article": "die"},
    {"word": "Arbeit", "article": "die"},
    {"word": "Beruf", "article": "der"},
    {"word": "Hobby", "article": "das"},
    {"word": "Sport", "article": "der"},
    {"word": "Musik", "article": "die"},
    {"word": "Film", "article": "der"},
    {"word": "Lied", "article": "das"},
    {"word": "Kunst", "article": "die"},
    {"word": "Geschichte", "article": "die"},
    {"word": "Kultur", "article": "die"},
    {"word": "Information", "article": "die"},
    {"word": "Nachricht", "article": "die"},
    {"word": "Brief", "article": "der"},
    {"word": "E-Mail", "article": "die"},
    {"word": "Gespräch", "article": "das"},
    {"word": "Anruf", "article": "der"},
    {"word": "Meinung", "article": "die"},
    {"word": "Grund", "article": "der"},
    {"word": "Teil", "article": "der"},
    {"word": "System", "article": "das"},
    {"word": "Methode", "article": "die"},
    {"word": "Form", "article": "die"},
    {"word": "Beispiel", "article": "das"},
    {"word": "Regel", "article": "die"},
    {"word": "Freiheit", "article": "die"},
    {"word": "Sicherheit", "article": "die"},
    {"word": "Gefahr", "article": "die"},
    {"word": "Erfolg", "article": "der"},
    {"word": "Fehler", "article": "der"},
    {"word": "Versuch", "article": "der"},
    {"word": "Erfahrung", "article": "die"},
    {"word": "Wissen", "article": "das"},
    {"word": "Wissenschaft", "article": "die"},
    {"word": "Bildung", "article": "die"},
    {"word": "Prüfung", "article": "die"},
    {"word": "Ergebnis", "article": "das"},
    {"word": "Preis", "article": "der"},
    {"word": "Wert", "article": "der"},
    {"word": "Vertrag", "article": "der"},
    {"word": "Termin", "article": "der"},
    {"word": "Veranstaltung", "article": "die"},
    {"word": "Fest", "article": "das"},
    {"word": "Feier", "article": "die"},
    {"word": "Urlaub", "article": "der"},
    {"word": "Reise", "article": "die"},
    {"word": "Ausflug", "article": "der"},
    {"word": "Richtung", "article": "die"},
    {"word": "Weg", "article": "der"},
    {"word": "Entfernung", "article": "die"},
    {"word": "Zukunft", "article": "die"},
    {"word": "Gegenwart", "article": "die"},
    {"word": "Vergangenheit", "article": "die"},
    {"word": "Geburtstag", "article": "der"},
    {"word": "Hochzeit", "article": "die"},
    {"word": "Wunsch", "article": "der"},
    {"word": "Hoffnung", "article": "die"},
    {"word": "Wahrheit", "article": "die"},
    {"word": "Lüge", "article": "die"},
    {"word": "Geheimnis", "article": "das"},
    {"word": "Kraft", "article": "die"},
    {"word": "Energie", "article": "die"},
    {"word": "Gesundheit", "article": "die"},
    {"word": "Krankheit", "article": "die"},
    {"word": "Schmerz", "article": "der"},
    {"word": "Medizin", "article": "die"},
    {"word": "Bewegung", "article": "die"},
    {"word": "Stimme", "article": "die"},
    {"word": "Geruch", "article": "der"},
    {"word": "Geschmack", "article": "der"},
    {"word": "Blick", "article": "der"},
    {"word": "Geräusch", "article": "das"},
    {"word": "Nummer", "article": "die"},
    {"word": "Zahl", "article": "die"},
    {"word": "Menge", "article": "die"},
    {"word": "Stück", "article": "das"},
    {"word": "Gruppe", "article": "die"},
    {"word": "Reihe", "article": "die"},
    {"word": "Liste", "article": "die"},
    {"word": "Seite", "article": "die"},
    {"word": "Ende", "article": "das"},
    {"word": "Anfang", "article": "der"},
    {"word": "Mitte", "article": "die"},
    {"word": "Rand", "article": "der"},
    {"word": "Hintergrund", "article": "der"},
    {"word": "Vordergrund", "article": "der"},
    {"word": "Boden", "article": "der"},
    {"word": "Stufe", "article": "die"},
    {"word": "Treppe", "article": "die"},
    {"word": "Aufzug", "article": "der"},
    {"word": "Ausgang", "article": "der"},
    {"word": "Eingang", "article": "der"},
    {"word": "Erlaubnis", "article": "die"},
    {"word": "Verbot", "article": "das"},
    {"word": "Strafe", "article": "die"},
    {"word": "Gericht", "article": "das"},
    {"word": "Anwalt", "article": "der"},
    {"word": "Polizei", "article": "die"},
    {"word": "Polizist", "article": "der"},
    {"word": "Krieg", "article": "der"},
    {"word": "Frieden", "article": "der"},
    {"word": "Quittung", "article": "die"},
    {"word": "Rechnung", "article": "die"},
    {"word": "Konto", "article": "das"},
    {"word": "Automat", "article": "der"},
    {"word": "Gewinn", "article": "der"},
    {"word": "Verlust", "article": "der"}
]

# 3. Russian Word List (300+ common Russian nouns)
RUSSIAN_WORDS = [
    "яблоко", "дом", "вода", "машина", "книга", "дерево", "солнце", "луна", "звезда", "собака",
    "кошка", "птица", "рыба", "город", "страна", "стол", "стул", "кровать", "дверь", "окно",
    "ключ", "хлеб", "сыр", "молоко", "кофе", "чай", "часы", "телефон", "компьютер", "школа",
    "ребенок", "человек", "мужчина", "женщина", "отец", "мать", "брат", "сестра", "друг", "голова",
    "рука", "нога", "глаз", "ухо", "нос", "рот", "сердце", "ночь", "день", "утро", "вечер",
    "неделя", "месяц", "год", "лето", "зима", "весна", "осень", "дождь", "снег", "ветер",
    "огонь", "лед", "пляж", "море", "озеро", "река", "гора", "лес", "парк", "цветок",
    "лист", "трава", "сад", "велосипед", "поезд", "автобус", "самолет", "корабль", "мост", "улица",
    "картина", "зеркало", "лампа", "сумка", "очки", "бутылка", "стакан", "тарелка", "чашка", "нож",
    "вилка", "ложка", "кастрюля", "сковорода", "подушка", "одеяло", "полотенце", "мыло", "щетка", "шкаф",
    "комната", "кухня", "ванная", "сад", "деревня", "деньги", "карта", "билет", "газета", "журнал",
    "зонт", "рюкзак", "одежда", "платье", "брюки", "рубашка", "футболка", "свитер", "куртка", "пальто",
    "обувь", "носок", "шляпа", "мальчик", "девочка", "сын", "дочь", "дядя", "тетя", "дедушка",
    "бабушка", "гость", "игрок", "король", "королева", "покупатель", "сосед", "семья", "начальник", "университет",
    "офис", "фирма", "магазин", "рынок", "ресторан", "отель", "больница", "аптека", "банк", "вокзал",
    "аэропорт", "площадь", "остров", "церковь", "музей", "театр", "кино", "библиотека", "столица", "почта",
    "пекарня", "кафе", "облако", "свет", "тень", "мышь", "слон", "лев", "медведь", "обезьяна",
    "лиса", "волк", "овца", "корова", "свинья", "курица", "утка", "пчела", "паук", "комар",
    "бабочка", "змея", "лягушка", "кролик", "лошадь", "дельфин", "курица", "колбаса", "овощи", "фрукты",
    "банан", "апельсин", "картофель", "помидор", "салат", "суп", "соус", "рис", "макароны", "сахар",
    "соль", "перец", "масло", "уксус", "торт", "шоколад", "орех", "мед", "варенье", "жизнь",
    "любовь", "счастье", "радость", "страх", "сон", "мысль", "идея", "проблема", "решение", "вопрос",
    "ответ", "слово", "язык", "работа", "профессия", "хобби", "спорт", "музыка", "фильм", "песня",
    "искусство", "история", "культура", "информация", "новость", "письмо", "звонок", "мнение", "причина", "часть",
    "система", "метод", "форма", "пример", "правило", "свобода", "безопасность", "опасность", "успех", "ошибка",
    "опыт", "знание", "наука", "образование", "экзамен", "результат", "цена", "стоимость", "договор", "встреча",
    "праздник", "отпуск", "путешествие", "направление", "дорога", "расстояние", "будущее", "настоящее", "прошлое", "день",
    "рождения", "свадьба", "желание", "надежда", "правда", "ложь", "тайна", "сила", "энергия", "здоровье",
    "болезнь", "боль", "лекарство", "движение", "голос", "запах", "вкус", "взгляд", "звук", "номер",
    "число", "количество", "кусок", "группа", "ряд", "список", "страница", "конец", "начало", "середина",
    "край", "фон", "пол", "ступень", "лестница", "лифт", "выход", "вход", "разрешение", "запрет",
    "штраф", "суд", "адвокат", "полиция", "полицейский", "война", "мир", "чек", "счет", "аккаунт",
    "автомат", "прибыль", "убыток", "монета", "бумага", "ручка", "карандаш", "портфель", "часы", "кольцо"
]

def main():
    # Save English JSON
    en_path = os.path.join(APP_WORDS_DIR, "en.json")
    with open(en_path, "w", encoding="utf-8") as f:
        json.dump(ENGLISH_WORDS, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(ENGLISH_WORDS)} English words -> {en_path}")

    # Save German JSON
    de_path = os.path.join(APP_WORDS_DIR, "de.json")
    with open(de_path, "w", encoding="utf-8") as f:
        json.dump(GERMAN_WORDS, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(GERMAN_WORDS)} German words with articles -> {de_path}")

    # Save Russian JSON
    ru_path = os.path.join(APP_WORDS_DIR, "ru.json")
    with open(ru_path, "w", encoding="utf-8") as f:
        json.dump(RUSSIAN_WORDS, f, ensure_ascii=False, indent=2)
    print(f"Generated {len(RUSSIAN_WORDS)} Russian words -> {ru_path}")

    # Save index.ts
    index_path = os.path.join(APP_WORDS_DIR, "index.ts")
    index_content = """import en from './en.json'
import de from './de.json'
import ru from './ru.json'

export type WordItem = string | { word: string; article?: string }

export const wordPools: Record<string, WordItem[]> = {
  en,
  de,
  ru
}

export default wordPools
"""
    with open(index_path, "w", encoding="utf-8") as f:
        f.write(index_content)
    print(f"Generated index.ts -> {index_path}")

    # Save legacy words.json for root app compatibility if needed
    legacy_words_path = os.path.join(os.path.dirname(__file__), "../app/words.json")
    with open(legacy_words_path, "w", encoding="utf-8") as f:
        json.dump(ENGLISH_WORDS, f, ensure_ascii=False, indent=2)
    print(f"Updated legacy words.json -> {legacy_words_path}")

if __name__ == "__main__":
    main()
